band_1: g
band_2: r
batch:
  max_jobs: 20
catalog:
  basis_1: ra
  basis_2: dec
  mag: 'mag_{}'
  mag_dered: 'mag_{}'
  mag_err: 'magerr_{}'
  mag_max: 26
  nside: 32
  profile: null
isochrone:
  age: 12
  metallicity: 0.0001
  name: Bressan2012
  survey: des
output:
  candidate_list: candidate_list.csv
  log_dir: log_dir
  results_dir: results_dir
  save_dir: plot_dir
survey:
  fracdet: null
  name: lsst
  sim_dir: /project/shared/data/satsim/lsst_dc2_v6/

